### ISSUE TITLE
Zero Sol/s

### ISSUE THREAD

**Issue by kozyilmaz** [kozyilmaz/nheqminer-macos#10]
quoting @eshbeata
```
i'm using the built release it worked with the old cuda not sure why
and it always [23:28:37][0x00007fffe30433c0] Speed [15 sec]: 0 I/s, 0 Sols/s
Any specific solution here?
```
1. What is your graphics card?
1. Which miner (nheqminer-cpu, gpu or old) are you using? 
2. Do you have CUDA toolkit installed?
3. What is your CUDA driver version (System Preference)?
4. Can you paste the output of the following commands (only the miner you'll be using is enough)
```
$ ./nheqminer-gpu -ci
$ ./nheqminer-old -b -cd 0 -cv 1
$ ./nheqminer-gpu -b -cd 0
```

**Comment by Edig** [comment]
I received 
Speed [15 sec]: 1.13333 I/s, 1.73333 Sols/s

way less than my CPU. I know my GPU is not really god but should do better than that. (I will upgraded it soon, but in the mean time I wanto to use this one)

NVIDIA GeForce GT 750M 2048 MB
miner: OLD
Yes I do have CUDA installed
CUDA Version: 8.0.83

`
	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.5c
	Thanks to Zcash developers for providing base of the code.
	    Special thanks to tromp, xenoncat and djeZo for providing 
	      optimized CPU and CUDA equihash solvers.
	==================== www.nicehash.com ====================

Number of CUDA devices found: 1
	#0 GeForce GT 750M | SM version: 3.0 | SM count: 2`

`Eduardos-MacBook-Pro:miner eduardo$ ./nheqminer-old -b -cd 0 -cv 1

	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.5c
	Thanks to Zcash developers for providing base of the code.
	    Special thanks to tromp, xenoncat and djeZo for providing 
	      optimized CPU and CUDA equihash solvers.
	==================== www.nicehash.com ====================

Setting log level to 2
[21:22:18][0x00007fffc945c3c0] Using SSE2: YES
[21:22:18][0x00007fffc945c3c0] Using AVX: YES
[21:22:18][0x00007fffc945c3c0] Using AVX2: YES
[21:22:18][0x00007fffc945c3c0] Benchmarking CUDA worker (CUDA-TROMP) GeForce GT 750M (#0) BLOCKS=14, THREADS=64
[21:22:19][0x00007fffc945c3c0] Benchmark starting... this may take several minutes, please wait...
[21:24:31][0x00007fffc945c3c0] Benchmark done!
[21:24:31][0x00007fffc945c3c0] Total time : 131502 ms
[21:24:31][0x00007fffc945c3c0] Total iterations: 200
[21:24:31][0x00007fffc945c3c0] Total solutions found: 393
[21:24:31][0x00007fffc945c3c0] Speed: 1.52089 I/s
[21:24:31][0x00007fffc945c3c0] Speed: 2.98855 Sols/s
Eduardos-MacBook-Pro:miner eduardo$ ./nheqminer-gpu -b -cd 0

	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.5c
	Thanks to Zcash developers for providing base of the code.
	    Special thanks to tromp, xenoncat and djeZo for providing 
	      optimized CPU and CUDA equihash solvers.
	==================== www.nicehash.com ====================

Setting log level to 2
[21:24:37][0x00007fffc945c3c0] Using SSE2: YES
[21:24:37][0x00007fffc945c3c0] Using AVX: YES
[21:24:37][0x00007fffc945c3c0] Using AVX2: YES
[21:24:37][0x00007fffc945c3c0] Only CUDA devices with SM 5.0 and higher are supported.`

**Comment by kozyilmaz** [comment]
@Edig unfortunately currently best nheqminer GPU solvers supports Compute Capability > 5.0 (you may check the list here https://developer.nvidia.com/cuda-gpus) which means GeForce 9xx series minimum.

I added older Tromp GPU solver builds (nheqminer-old), although they work on older GPU's (and sometimes don't) the hashrate is not really good. 

I will suggest giving an OpenCL miner a try (https://github.com/justvanbloom/silentarmy), @denics recommended this in one of the closed issues.

Hope that helps.

**Comment by kozyilmaz** [comment]
SM 3.0 is supported starting https://github.com/kozyilmaz/nheqminer-macos/commit/786a2c8cd33e6052672d95bb626987bef1720479
