### ISSUE TITLE
OpenCL support for AMD

### ISSUE THREAD

**Issue by jasin755** [kozyilmaz/nheqminer-macos#12]
Hi, do you plan add OpenCL support for AMD graphic cards ?

**Comment by kozyilmaz** [comment]
As far as I see nheqminer's original authors have no plans to support OpenCL and unfortunately I also can not add OpenCL support in near future. You may try https://github.com/justvanbloom/silentarmy though, it should work on macOS.

Hope that helps!

**Comment by kozyilmaz** [comment]
OpenCL is not supported at the moment, maybe in the future!
