### ISSUE TITLE
Does nheqminer support OpenCL

### ISSUE THREAD

**Issue by denics** [kozyilmaz/nheqminer-macos#2]
Hi @kozyilmaz , many mac come with AMD graphic cards, are you going to support OpenCL or only CUDA?

**Comment by kozyilmaz** [comment]
@denics nheqminer as of 0.5c supports only CUDA, however there are other miners utilizing OpenCL like "silentarmy" (https://github.com/mbevand/silentarmy) but I didn't see any macOS builds for those.

**Comment by denics** [comment]
This version runs ok on Mac https://github.com/justvanbloom/silentarmy

**Comment by kozyilmaz** [comment]
good, will take a look to it sometime. In the meantime I have no plans to add OpenCL support to nheqminer
