### ISSUE TITLE
xcode 9.2 not CUDA 9 compatible

### ISSUE THREAD

**Issue by Olvikolvi** [kozyilmaz/nheqminer-macos#21]
$ make
Software Version:
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
Compiler Version:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Found CUDA installation: /usr/local/cuda, version unknown
NVCC Version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:08:57_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
Using CUDA 9 Toolkit
CUDA 9 compatible 'Command Line Tools for Xcode 8.3.2' not found!
Download and install 'Command Line Tools for Xcode 8.3.2' from 'https://developer.apple.com/download/more'
After installation run command below to switch to CUDA Toolkit compatible command line tools
  $ sudo xcode-select -switch /Library/Developer/CommandLineTools
Run command below to switch back to latest command line tools
  $ sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
make: *** [syscheck] Error 1

**Comment by kozyilmaz** [comment]
Hi @Olvikolvi, these compiler restrictions are imposed by Nvidia. As printed in the error log please install CUDA 9 compatible "Xcode Command Line Tools" (not complete Xcode) and after your binaries are created you can upgrade it back to normal.

Or you can use precompiled versions. Hope that helps!

**Comment by Olvikolvi** [comment]
Precompiled is just fine for me. Now I noticed its existence 👍
