### ISSUE TITLE
Clang version

### ISSUE THREAD

**Issue by gmickel** [kozyilmaz/nheqminer-macos#3]
Hi there

FIrst off, thanks for the great work!

It may be worth noting that I wasn't able to make the project using the newer command line tools version (Apple LLVM version 8.1.0 (clang-802.0.42)). 

The build worked perfectly after downloading the following older version:

For macOS 10.12, XCode 8.2:
http://adcdownload.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.12_for_Xcode_8.2/Command_Line_Tools_macOS_10.12_for_Xcode_8.2.dmg

*edit*: I see now that this is specified in the Readme in the miner folder.

PS. Perhaps of interest to some, I'm getting around 600 Sols/s on a 1080Ti

**Comment by kozyilmaz** [comment]
Hi @gmickel;

Good point, CUDA Toolkit is tied to the clang versions at it's release time. I'll extend README for managing multiple command line tools and select the correct one for nheqminer builds.

Great solution rate btw!

**Comment by kozyilmaz** [comment]
Commit 8ec28182b427475661024464d9c5c854b472ca84 closes #3
