### ISSUE TITLE
CUDA Mining requires SM 5.0

### ISSUE THREAD

**Issue by TheMCTipers** [kozyilmaz/nheqminer-macos#6]
MacOS 10.12.5, 'Sierra'
GTX 760 

After compiling nheqminer-gpu, i tried to run this:
./nheqminer-gpu -b -cd 0 (to benchmark it)

It gives me this:

	==================== www.nicehash.com ====================
		Equihash CPU&GPU Miner for NiceHash v0.5c
	Thanks to Zcash developers for providing base of the code.
	    Special thanks to tromp, xenoncat and djeZo for providing 
	      optimized CPU and CUDA equihash solvers.
	==================== www.nicehash.com ====================

Setting log level to 2
[14:45:46][0x00007fffa59573c0] Using SSE2: YES
[14:45:46][0x00007fffa59573c0] Using AVX: YES
[14:45:46][0x00007fffa59573c0] Using AVX2: NO
[14:45:46][0x00007fffa59573c0] Only CUDA devices with SM 5.0 and higher are supported.

Is it possible to mine zcash using my 760? Or is it a no go ..

**Comment by kozyilmaz** [comment]
@TheMCTipers nheqminer switched to "Djezo" for CUDA that requires at least SM 5.0. I can create a separate "trompgpu" miner that supports older versions but hash rate won't be that good. Let me look into it.

**Comment by TheMCTipers** [comment]
Alright, thanks!

**Comment by kozyilmaz** [comment]
@TheMCTipers ok I added a separate binary name `nheqminer-old` that contains only Tromp CUDA solver without the SM 5.0 requirement. You can try it like the command below, just don't forget `-cv 1` for Tromp solver
```
./nheqminer-old -l POOL_ADDRESS -u WORKER -p PASSWORD -cd 0 -cv 1
```

**Comment by TheMCTipers** [comment]
How do I use this with the NiceHash service? Or is it not possible?

**Comment by kozyilmaz** [comment]
@TheMCTipers If you check `README.txt` or `miner.sh` in `nheqminer-macos/miner`directory you'll see some usage examples with different pools. Commands below should probably work for nicehash.
```
./nheqminer-cpu -l equihash.eu.nicehash.com:3357 -u YOUR_BITCOIN_ADDRESS.worker1 -t THREAD_COUNT
./nheqminer-old -l equihash.eu.nicehash.com:3357 -u YOUR_BITCOIN_ADDRESS.worker1 -cd 0 -cv 1
```

**Comment by TheMCTipers** [comment]
Alright, well I am getting 10.1333 Sols/s on my 760 now.
That's half the speed I get with my CPU (20 Sols/s), and it consumes much more power.

**Comment by kozyilmaz** [comment]
@TheMCTipers unfortunately for nheqminer that's the case, at least everything is working

**Comment by kozyilmaz** [comment]
@TheMCTipers Can you give it a try with v5? I added support for SM30 GPU's to Djezo Solver 
https://github.com/kozyilmaz/nheqminer-macos/releases/tag/v5

**Comment by TheMCTipers** [comment]
Don't have a working hackintosh anymore. Broke it, didn't decide to fix it, went back to shitdows for now. Will probably go back to trying to get high Sierra to run when shitdows breaks again.

**Comment by kozyilmaz** [comment]
SM 3.0 is supported starting https://github.com/kozyilmaz/nheqminer-macos/commit/786a2c8cd33e6052672d95bb626987bef1720479

**Comment by andrepradotf** [comment]
sorry to ask, but what actually is this SM 5.0 ?

**Comment by kozyilmaz** [comment]
Hi @andrepradotf It is the "compute capability" determined by Nvidia, a feature set, here is the list check out GeForce GPU's:
https://developer.nvidia.com/cuda-gpus
