### ISSUE TITLE
-u is a bitcoinaddress only?

### ISSUE THREAD

**Issue by MaximusMcCann** [kozyilmaz/nheqminer-macos#7]
Can I Use a zcash address here?

**Comment by kozyilmaz** [comment]
@MaximusMcCann for nicehash, Bitcoin address is required (check section 3.5 of https://www.nicehash.com/index.jsp?p=software). There are plenty of options for Zcash mining that you can use your Zcash address, check out https://zcash.flypool.org or https://zec.suprnova.cc

**Comment by MaximusMcCann** [comment]
@kozyilmaz cheers.  Been looking for a mac Cuda version...
