### ISSUE TITLE
Getting low hash rate (~15 sols/s) on 970 gpu

### ISSUE THREAD

**Issue by drhaynes** [kozyilmaz/nheqminer-macos#8]
Running the miner with `nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u BITCOIN_ADDRESS.worker1 -cd 0 -cb 16 -ct 128`

I am only getting approx 15 sols/s, but would be expecting more like 200 for this card.

Is there something I am doing wrong?

I'm using the latest release build from: https://github.com/kozyilmaz/nheqminer-macos/releases/tag/v4

**Comment by kozyilmaz** [comment]
@drhaynes you are right, I own a GTX 960 and I get around ~130 Sol/s

1. Do you still see 15 Sol/s with  `nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u BITCOIN_ADDRESS.worker1 -cd 0 `

2. Can you also paste the outputs of:
`./nheqminer-gpu -ci`
`ls -lrt /usr/local/cuda/lib/libcuda.dylib`

**Comment by dansolo** [comment]
@kozyilmaz Sorry to hijack the thread but I'm having the same issue with a GTX 970 on the latest build.

Tried "nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u BITCOIN_ADDRESS.worker1 -cd 0" and am still seeing ~15 sols/s

The output I get from "./nheqminer-gpu -ci ls -lrt /usr/local/cuda/lib/libcuda.dylib" is:

Number of CUDA devices found: 1
	#0 GeForce GTX 970 | SM version: 5.2 | SM count: 13

**Comment by kozyilmaz** [comment]
@dansolo can you execute them separately?

`$ ./nheqminer-gpu -ci`
`$ ls -lrt /usr/local/cuda/lib/libcuda.dylib`

and can you please try with v3 release too?

**Comment by kozyilmaz** [comment]
@drhaynes @dansolo guys, can you also paste the log output after you run:
`$ nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u YOUR_BTC_ADDR.rig1 -cd 0 -d 0`

**Comment by dansolo** [comment]
Result from "ls -lrt /usr/local/cuda/lib/libcuda.dylib":

-rwxr-xr-x  1 root  wheel  13504 12 Jan 12:31 /usr/local/cuda/lib/libcuda.dylib

Still getting ~15 Sols/s on v3 using "nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u BITCOIN_ADDRESS.worker1 -cd 0"

**Comment by kozyilmaz** [comment]
@dansolo can you send me the whole console output of mining command, please delete/substitute your Bitcoin wallet address
`$ nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u YOUR_BTC_ADDR.rig1 -cd 0 -d 0`

**Comment by dansolo** [comment]
@kozyilmaz I've attached the output for 

`$ nheqminer-gpu -l equihash.eu.nicehash.com:3357 -u YOUR_BTC_ADDR.rig1 -cd 0 -d 0`

[nheqminer_output.txt](https://github.com/kozyilmaz/nheqminer-macos/files/1089614/nheqminer_output.txt)

**Comment by drhaynes** [comment]
After building the latest from master this morning, I am now seeing performance as expected.

As part of the build deps, I installed the cuda toolkit v.8.0.61 from https://developer.nvidia.com/cuda-downloads, as it wasn't already present, so maybe that had something to do with the issue.

**Comment by kozyilmaz** [comment]
@drhaynes thanks a lot for the update, I was about the reply that I have to dig into Nvidia driver versions but it's good to know at least a workaround exist.

So either:
1. CUDA toolkit contains some libraries/binaries that are needed but I failed to identify them, I'll try uninstalling CUDA toolkit and try to reproduce
2. CUDA toolkit comes with an older Nvidia driver and this driver perform significantly better

Can you post CUDA and GPU driver version in your "System Preferences" if you don't mind. Thanks!

**Comment by drhaynes** [comment]
Sure, versions below.

From the Nvidia prefs pane:
NVIDIA Web Driver: 378.05.05.15f101

From the Cuda prefs pane:
CUDA Driver Version: 8.0.61
GPU Driver Version: 10.18.5 (378.05.05.15f101)

**Comment by drhaynes** [comment]
Incidentally, I can see there is now a cuda update available (to version 8.0.83) in the Cuda prefs pane. I'm wondering if I was on that version before installing the toolkit manually.

**Comment by kozyilmaz** [comment]
@dansolo maybe you can solve this mystery for us, what are you CUDA and GPU driver versions while having low hash rate?

**Comment by dansolo** [comment]
@kozyilmaz I'm on:
CUDA Driver Version Version: 8.0.61
NVIDIA Web Driver: 346.03.15f02

**Comment by kozyilmaz** [comment]
@dansolo sorry for the inconvenience but can you try installing CUDA toolkit (https://developer.nvidia.com/cuda-downloads) ?

I will uninstall CUDA toolkit and try to reproduce the issue as soon as I have access to my mining Mac (a couple days tops).

**Comment by drhaynes** [comment]
Some more info on this issue.

I upgraded the Xcode command line tools. Everything was fine until restarting, then I was back to 15 sols/s.

Maybe one of the dynamic libraries in the latest command line tools is causing the issue?

**Comment by drhaynes** [comment]
Reinstalling the old Xcode dev tools didn't fix it, but reinstalling them and then the CUDA toolkit and rebuilding did.

**Comment by dansolo** [comment]
@drhaynes Great work! Can you let me know which version of the Xcode dev tools you used?

**Comment by dansolo** [comment]
@kozyilmaz Quick update. Had no luck with the Cuda re-install, so swapped to MacBook Pro on 10.12.5 and built it there with XCode 8.2.1/Command Line Tools 8.2. I ran into the Make issues which you solved for me with the "disable.patch.txt" file, and was able to transfer back to my Hackintosh for the full power of the GTX970 which is now running at 215 Sols/s. Thank you ^ 1M for your work on this. Donation inbound when I get my first payout.

**Comment by kozyilmaz** [comment]
@drhaynes great detective work! It's interesting that it didn't work unless you build with vanilla CUDA toolkit 8.0.61 and correct dev tools. I'll get to the bottom of this but thank you for your work & time.

@dansolo great news, glad I can help!

**Comment by eshbeata** [comment]
Hi 
i'm using the built release it worked with the old cuda not sure why 
and it always [23:28:37][0x00007fffe30433c0] Speed [15 sec]: 0 I/s, 0 Sols/s
Any specific solution here?

**Comment by kozyilmaz** [comment]
@drhaynes Hey I am unable to reproduce your findings with GTX 960, here is what I tried, any suggestions?


1. macOS 10.12.5 (16F73), vanilla CUDA toolkit install (8.0.61) with accompanying CUDA (CUDA Driver Version: 8.0.61) and Nvidia driver (GPU Driver Version: 10.18.5 (378.05.05.15f01) plus older Xcode 8.2 command line tools (clang-800.0.42.1). Reboot, do a fresh nheqminer-macos build, run miner and hashrate for GTX 960 is:
```
Speed [15 sec]: 68 I/s, 127.333 Sols/s
```

2. Reboot without touching miner binaries (CUDA driver 8.0.61, clang-800.0.42.1), run miner again, hashrate below:
```
Speed [15 sec]: 67.9333 I/s, 127.8 Sols/s
```

3. Upgrade Xcode command line tools (CUDA driver 8.0.61, clang-802.0.42) without touching miner binaries and without rebooting run miner again, hashrate below:
```
Speed [15 sec]: 67.9333 I/s, 125.933 Sols/s
```

4. Reboot machine without touching miner binaries with new Xcode tools (CUDA driver 8.0.61, clang-802.0.42). Run miner after reboot, hashrate below:
```
Speed [15 sec]: 67.9333 I/s, 124.4 Sols/s
```

5. Upgrade CUDA driver while having latest Xcode tools (CUDA driver 8.0.83, clang-802.0.42) and run miner without rebooting:
```
Speed [15 sec]: 67.8 I/s, 129.867 Sols/s
```

6. Reboot and use latest CUDA driver and Xcode tools (CUDA driver 8.0.83, clang-802.0.42) and run miner again:
```
Speed [15 sec]: 64.6 I/s, 123.4 Sols/s
```

**Comment by kozyilmaz** [comment]
@eshbeata let's discuss your problem in issue #10

**Comment by kozyilmaz** [comment]
cleaning up issues, appreciate a report with new releases if problem still persists
